USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE DATABASE RETAIL_DB;


CREATE OR REPLACE SCHEMA RETAIL_DB.RAW;
CREATE OR REPLACE SCHEMA RETAIL_DB.ANALYTICS;

CREATE OR REPLACE WAREHOUSE RETAIL_WH
WITH 
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

USE WAREHOUSE RETAIL_WH;


// CREATE RAW TABLE

USE DATABASE RETAIL_DB;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW_SALES (
    ORDER_ID INT,
    ORDER_DATE DATE,
    CUSTOMER_NAME STRING,
    PRODUCT STRING,
    QUANTITY INT, 
    UNIT_PRICE NUMBER(10,2),
    STORE_CITY STRING,
    LOAD_DATE DATE
);


//CREATE FINAL TABLE

USE DATABASE RETAIL_DB;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE FINAL_SALES (
    ORDER_ID INT,
    ORDER_DATE DATE,
    CUSTOMER_NAME STRING,
    PRODUCT STRING,
    QUANTITY INT, 
    UNIT_PRICE NUMBER(10,2),
    STORE_CITY STRING,
    LOAD_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

// create fact TABLE
CREATE OR REPLACE TABLE RETAIL_DB.ANALYTICS.FACT_SALES
(
    ORDER_ID INT,
    ORDER_DATE DATE,
    CUSTOMER_NAME STRING,
    PRODUCT STRING,
    QUANTITY INT,
    UNIT_PRICE NUMBER(10,2),
    TOTAL_AMOUNT NUMBER(10,2),
    STORE_CITY STRING,
    SALES_CATEGORY STRING,
    LOAD_DATE TIMESTAMP_NTZ
);



//STAGE SETUP

USE ROLE ACCOUNTADMIN;
USE DATABASE RETAIL_DB;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT CSV_FILE_FORMAT
TYPE = CSV 
FIELD_DELIMITER = ','
SKIP_HEADER = 1 
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

// CREATE EXTERNAL STAGE

CREATE OR REPLACE STAGE AZURE_SALES_STAGE
URL = 'azure://sonalistoragesales.blob.core.windows.net/retail-data/processed/sales/'
CREDENTIALS = (AZURE_SAS_TOKEN = 'sv=2026-02-06&ss=bfqt&srt=sco&sp=rwdlacupyx&se=2026-05-23T15:45:59Z&st=2026-05-22T10:45:59Z&spr=https,http&sig=IVP0C7UlJBxJXC2iTPmsJhTDCGwptY7%2Bg9RDSP%2F6T1k%3D')
FILE_FORMAT = CSV_FILE_FORMAT;


LIST @AZURE_SALES_STAGE;

USE DATABASE RETAIL_DB;
USE SCHEMA RAW;

truncate table raw_sales;
// script activity (load from ADF to snowflake)
COPY INTO RAW_SALES (
    ORDER_ID,
    ORDER_DATE,
    CUSTOMER_NAME,
    PRODUCT,
    QUANTITY,
    UNIT_PRICE,
    STORE_CITY,
    LOAD_DATE
)
FROM @AZURE_SALES_STAGE
PATTERN = '.*[.]csv'
FILE_FORMAT = CSV_FILE_FORMAT
ON_ERROR = 'CONTINUE';


SELECT * FROM RAW_SALES;



// SNOWPARK TRANSFORMATION

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE RETAIL_WH;
USE DATABASE RETAIL_DB;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE PROCEDURE SP_TRANSFORM_SALES()
RETURNS STRING
LANGUAGE PYTHON
RUNTIME_VERSION = '3.11'
PACKAGES = ('snowflake-snowpark-python')
HANDLER = 'main'
AS
$$
from snowflake.snowpark.functions import col, when

def main(session):

    raw_df = session.table("RETAIL_DB.RAW.RAW_SALES")

    final_df = raw_df.select(
        col("ORDER_ID"),
        col("ORDER_DATE"),
        col("CUSTOMER_NAME"),
        col("PRODUCT"),
        col("QUANTITY"),
        col("UNIT_PRICE"),
        (col("QUANTITY") * col("UNIT_PRICE")).alias("TOTAL_AMOUNT"),
        col("STORE_CITY"),
        when((col("QUANTITY") * col("UNIT_PRICE")) >= 50000, "HIGH_VALUE")
            .otherwise("NORMAL")
            .alias("SALES_CATEGORY"),
        col("LOAD_DATE")
    )

    final_df.write.mode("overwrite").save_as_table("RETAIL_DB.ANALYTICS.FACT_SALES")

    return "Sales transformation completed successfully."
$$;


// CALL SNOWPARK PROCEDURE

CALL RETAIL_DB.ANALYTICS.SP_TRANSFORM_SALES();

SELECT * FROM RETAIL_DB.ANALYTICS.FACT_SALES;


truncate table retail_db.analytics.fact_sales;

select * from RETAIL_DB.RAW.RAW_SALES;

drop database retail_db;