CREATE OR REPLACE WAREHOUSE HEALTHCARE_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

ALTER WAREHOUSE HEALTHCARE_WH
SET WAREHOUSE_SIZE= SMALL;

ALTER WAREHOUSE HEALTHCARE_WH
SET WAREHOUSE_SIZE= 'XSMALL';

ALTER WAREHOUSE HEALTHCARE_WH RESUME;
ALTER WAREHOUSE HEALTHCARE_WH SUSPEND;


CREATE OR REPLACE DATABASE HEALTHCARE_DB;

USE HEALTHCARE_DB;
CREATE OR REPLACE SCHEMA HEALTHCARE_DB.APPOINTMENT_SCHEMA;


CREATE OR REPLACE FILE FORMAT CSV_FILE_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1;


// internal stage
CREATE OR REPLACE STAGE APPOINTMENT_STAGE
FILE_FORMAT = CSV_FILE_FORMAT;

LIST @APPOINTMENT_STAGE;


// CREATE RAW TABLE
CREATE OR REPLACE TABLE APPOINTMENT_RAW (
    PatientId number,
    AppointmentId number,
    Gender string,
    ScheduledDay timestamp,
    AppointmentDay timestamp,
    Age int,
    Neighbourhood string,
    Scholarship INT,
    Hipertension int,
    Diabetes int,
    Alcoholism int,
    Handcap int,
    SMS_received int,
    No_Show string
);
select * from appointment_raw;


//LOAD DATA FROM STAGE TO RAW TABLE

COPY INTO APPOINTMENT_RAW
FROM @APPOINTMENT_STAGE
FILE_FORMAT = CSV_FILE_FORMAT
ON_ERROR = 'CONTINUE';

SELECT * FROM APPOINTMENT_RAW LIMIT 10;


//CREATE FINAL TABLE
CREATE OR REPLACE TABLE APPOINTMENT_FINAL (
    PATIENT_ID NUMBER,
    APPOINTMENT_ID NUMBER,
    GENDER STRING,
    AGE NUMBER,
    AGE_GROUP STRING,
    SCHEDULED_DATE DATE,
    APPOINTMENT_DATE DATE,
    WAITING_DAYS NUMBER,
    NEIGHBOURHOOD STRING,
    SCHOLARSHIP NUMBER,
    HYPERTENSION NUMBER,
    DIABETES NUMBER,
    ALCOHOLISM NUMBER,
    HANDICAP NUMBER,
    SMS_RECEIVED NUMBER,
    NO_SHOW_STATUS STRING,
    ATTENDANCE_STATUS STRING
);


//SNOWPARK PROCEDURE

CREATE OR REPLACE PROCEDURE LOAD_APPOINTMENT_FINAL()
RETURNS STRING
LANGUAGE PYTHON
RUNTIME_VERSION = '3.11'
PACKAGES = ('snowflake-snowpark-python')
HANDLER = 'main'
AS
$$
from snowflake.snowpark.functions import col, datediff, when, to_date

def main(session):

    raw_df = session.table("APPOINTMENT_RAW")

    transformed_df = raw_df.select(
        col("PATIENTID").alias("PATIENT_ID"),
        col("APPOINTMENTID").alias("APPOINTMENT_ID"),
        col("GENDER"),
        col("AGE"),

        when(col("AGE") < 13, "Child")
        .when(col("AGE") < 20, "Teen")
        .when(col("AGE") < 60, "Adult")
        .otherwise("Senior")
        .alias("AGE_GROUP"),

        to_date(col("SCHEDULEDDAY")).alias("SCHEDULED_DATE"),
        to_date(col("APPOINTMENTDAY")).alias("APPOINTMENT_DATE"),

        datediff(
            "day",
            to_date(col("SCHEDULEDDAY")),
            to_date(col("APPOINTMENTDAY"))
        ).alias("WAITING_DAYS"),

        col("NEIGHBOURHOOD"),
        col("SCHOLARSHIP"),
        col("HIPERTENSION").alias("HYPERTENSION"),
        col("DIABETES"),
        col("ALCOHOLISM"),
        col("HANDCAP").alias("HANDICAP"),
        col("SMS_RECEIVED"),

        col("NO_SHOW").alias("NO_SHOW_STATUS"),

        when(col("NO_SHOW") == "No", "Attended")
        .otherwise("Missed")
        .alias("ATTENDANCE_STATUS")
    )

    transformed_df.write.mode("overwrite").save_as_table("APPOINTMENT_FINAL")

    return "Data successfully loaded into APPOINTMENT_FINAL"
$$;

CALL LOAD_APPOINTMENT_FINAL();

SELECT * FROM APPOINTMENT_FINAL;


//CREATE STREAM
CREATE OR REPLACE STREAM APPOINTMENT_RAW_STREAM
ON TABLE APPOINTMENT_RAW;


//INSERT NEW RECORDS

INSERT INTO APPOINTMENT_RAW VALUES 
(91272491111121,5000000,'F','2016-04-29T18:38:08Z','2026-04-29T00:00:00Z',32,'JARDIM TA PENHA',0,1,0,1,0,0,'No'),
(91111191111121,5000011,'M','2026-04-27T10:51:45Z','2026-04-27T10:51:45Z',12,'REPÚBLICA',0,1,0,0,0,0,'No'),
(370000000001127,5444444,'F','2026-04-27T13:30:56Z','2026-06-07T00:00:00Z',54,'MARIA ORTIZ',0,0,0,0,0,1,'No');


SELECT * FROM APPOINTMENT_RAW_STREAM;

CALL LOAD_APPOINTMENT_FINAL();

SELECT * FROM APPOINTMENT_FINAL WHERE PATIENT_ID = 91272491111121;


//CREATE SNOWPIPE

CREATE OR REPLACE PIPE APPOINTMENT_PIPE
AUTO_INGEST = FALSE
AS 
COPY INTO APPOINTMENT_RAW
FROM @APPOINTMENT_STAGE
FILE_FORMAT = CSV_FILE_FORMAT
ON_ERROR = 'CONTINUE';

SHOW PIPES;

ALTER PIPE APPOINTMENT_PIPE REFRESH;



// CREATE REPORTING VIEW FOR POWERBI

CREATE OR REPLACE VIEW VW_APPOINTMENT_DASHBOARD AS
SELECT
    PATIENT_ID,
    APPOINTMENT_ID,
    GENDER,
    AGE,
    AGE_GROUP,
    SCHEDULED_DATE,
    APPOINTMENT_DATE,
    WAITING_DAYS,
    NEIGHBOURHOOD,
    SCHOLARSHIP,
    HYPERTENSION,
    DIABETES,
    ALCOHOLISM,
    HANDICAP,
    SMS_RECEIVED,
    NO_SHOW_STATUS,
    ATTENDANCE_STATUS
FROM APPOINTMENT_FINAL;

SELECT * FROM VW_APPOINTMENT_DASHBOARD LIMIT 20;


