// Warehouse setup

CREATE OR REPLACE WAREHOUSE MARKETING_WH
WITH WAREHOUSE_SIZE = 'X-SMALL'
WAREHOUSE_TYPE = 'STANDARD'
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE;

CREATE OR REPLACE WAREHOUSE FINANCE_WH
WITH WAREHOUSE_SIZE = 'X-SMALL'
WAREHOUSE_TYPE = 'STANDARD'
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE;

CREATE OR REPLACE WAREHOUSE ETL_WH 
WITH WAREHOUSE_SIZE = 'SMALL'
WAREHOUSE_TYPE = 'STANDARD'
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE;

DROP WAREHOUSE MARKETING_WH;
DROP WAREHOUSE FINANCE_WH;
DROP WAREHOUSE ETL_WH;



// Role setup

CREATE OR REPLACE ROLE MARKETING_ANALYST;
GRANT USAGE ON WAREHOUSE MARKETING_WH TO ROLE MARKETING_ANALYST;

CREATE OR REPLACE ROLE FINANCE_USER;
GRANT USAGE ON WAREHOUSE FINANCE_WH TO ROLE FINANCE_USER;

CREATE OR REPLACE ROLE ETL_DEVELOPER;
GRANT USAGE ON WAREHOUSE ETL_WH TO ROLE ETL_DEVELOPER;



// User setup

CREATE OR REPLACE USER MKT_USER1 PASSWORD = 'MKT_USER1' LOGIN_NAME = 'MKT_USER1' 
DEFAULT_ROLE = 'MARKETING_ANALYST' DEFAULT_WAREHOUSE= 'MARKETING_WH' MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE MARKETING_ANALYST TO USER MKT_USER1;

CREATE OR REPLACE USER FIN_USER1 PASSWORD = 'FIN_USER1' LOGIN_NAME = 'FIN_USER1'
DEFAULT_ROLE = 'FINANCE_USER' DEFAULT_WAREHOUSE = 'FINANCE_WH' MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE FINANCE_USER TO USER FIN_USER1;

CREATE OR REPLACE USER ETL_USER1 PASSWORD = 'ETL_USER1' LOGIN_NAME = 'ETL_USER1'
DEFAULT_ROLE = 'ETL_DEVELOPER' DEFAULT_WAREHOUSE = 'ETL_WH' MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE ETL_DEVELOPER TO USER ETL_USER1;

DROP USER MKT_USER1;
DROP USER FIN_USER1;
DROP USER ETL_USER1;

DROP ROLE MARKETING_ANALYST;
DROP ROLE FINANCE_USER;
DROP ROLE ETL_DEVELOPER;



// Create performance Demo database

CREATE OR REPLACE DATABASE RETAIL_MARKETING_DB;

select * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.STORE_SALES limit 10;
select * from SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER limit 10;
select * from SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.DATE_DIM limit 10;
select * from SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.ITEM limit 10;

CREATE OR REPLACE TABLE RETAIL_MARKETING_DB.PUBLIC.CAMPAIGN_SALES AS 
SELECT 
      ss.ss_customer_sk as customer_id,
      ss.ss_net_paid as amount_spent,
      ss.ss_quantity as quantity_sold,
      ss.ss_sales_price as sales_price,

      c.c_first_name as first_name,
      c.c_last_name as last_name,
      c.c_email_address as customer_email,
      c.c_birth_year as birth_year,

      i.i_item_sk as item_id,
      i.i_product_name as item_name,
      i.i_brand as item_brand,
      i.i_class as category,

      d.d_date as sale_date,
      d.d_year as sale_year,
      d.d_moy as sale_month

FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.STORE_SALES ss 
JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER c ON ss.ss_customer_sk = c.c_customer_sk
JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.ITEM i ON i.i_item_sk = ss.ss_item_sk
JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.DATE_DIM d ON d.d_date_sk = ss.ss_sold_date_sk
LIMIT 100000;

SELECT * FROM CAMPAIGN_SALES LIMIT 50;



// Grant permissions

GRANT USAGE ON DATABASE RETAIL_MARKETING_DB TO ROLE MARKETING_ANALYST;
GRANT USAGE ON SCHEMA RETAIL_MARKETING_DB.PUBLIC TO ROLE MARKETING_ANALYST;
GRANT SELECT ON TABLE RETAIL_MARKETING_DB.PUBLIC.CAMPAIGN_SALES TO ROLE MARKETING_ANALYST;

GRANT USAGE ON DATABASE RETAIL_MARKETING_DB TO ROLE FINANCE_USER;
GRANT USAGE ON SCHEMA RETAIL_MARKETING_DB.PUBLIC TO ROLE FINANCE_USER;
GRANT SELECT ON TABLE RETAIL_MARKETING_DB.PUBLIC.CAMPAIGN_SALES TO ROLE FINANCE_USER;

GRANT USAGE ON DATABASE RETAIL_MARKETING_DB TO ROLE ETL_DEVELOPER;
GRANT USAGE ON SCHEMA RETAIL_MARKETING_DB.PUBLIC TO ROLE ETL_DEVELOPER;

GRANT CREATE TABLE ON SCHEMA RETAIL_MARKETING_DB.PUBLIC TO ROLE ETL_DEVELOPER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA RETAIL_MARKETING_DB.PUBLIC TO ROLE ETL_DEVELOPER;



// Performance Testing

SELECT SALE_YEAR, CATEGORY, SUM(QUANTITY_SOLD) AS TOTAL_QUANTITY_SOLD, SUM(AMOUNT_SPENT) AS AMOUNT
FROM CAMPAIGN_SALES GROUP BY SALE_YEAR, CATEGORY
ORDER BY SALE_YEAR, TOTAL_QUANTITY_SOLD;

ALTER WAREHOUSE MARKETING_WH
SET WAREHOUSE_SIZE = 'SMALL';

ALTER WAREHOUSE MARKETING_WH
SET WAREHOUSE_SIZE = 'X-SMALL';



// Cache Testing

SELECT * FROM CAMPAIGN_SALES WHERE CATEGORY != 'optics';



// Cluster Key

SELECT * FROM CAMPAIGN_SALES WHERE SALE_DATE BETWEEN '2000-01-01' AND '2020-01-31';

ALTER TABLE CAMPAIGN_SALES
CLUSTER BY (SALE_DATE);