//CREATE DATABASE
CREATE OR REPLACE TRANSIENT DATABASE STREAMS_DB;
DROP DATABASE STREAMS_DB;

//CREATE RAW SALES STAGING TABLE
CREATE OR REPLACE TABLE STREAMS_DB.PUBLIC.SALES_RAW_STAGING (
    id int,
    product string,
    price decimal(10,2),
    amount int,
    store_id int
);

//INSERT INITIAL SALES DATA
INSERT INTO STREAMS_DB.PUBLIC.SALES_RAW_STAGING VALUES 
    (1, 'Banana', 1.99, 1, 1),
    (2, 'Lemon', 0.99, 1, 1),
    (3, 'Apple', 1.79, 1, 2),
    (4, 'Orange Juice', 1.89,null, 1),
    (5, 'Cereals', 5.98, 2, 1);
SELECT * FROM STREAMS_DB.PUBLIC.SALES_RAW_STAGING;


//CREATE STORE TABLE
CREATE OR REPLACE TABLE STREAMS_DB.PUBLIC.STORE_TABLE (
    store_id int,
    location string,
    employees int
);

//INSERT STORE DATA
INSERT INTO STREAMS_DB.PUBLIC.STORE_TABLE VALUES
    (1, 'Chicago', 33),
    (2, 'London', 12);
SELECT * FROM STREAMS_DB.PUBLIC.STORE_TABLE;


//CREATE FINAL SALES TABLE
CREATE OR REPLACE TABLE STREAMS_DB.PUBLIC.SALES_FINAL_TABLE (
    id int,
    product string,
    price decimal(10,2),
    amount int,
    store_id int,
    location string,
    employees int
);

//PERFORM INITIAL FULL LOAD
INSERT INTO STREAMS_DB.PUBLIC.SALES_FINAL_TABLE
SELECT 
    SALES.ID, SALES.PRODUCT, SALES.PRICE, SALES.AMOUNT,
    STORE.STORE_ID, STORE.LOCATION, STORE.EMPLOYEES
FROM STREAMS_DB.PUBLIC.SALES_RAW_STAGING SALES
JOIN STREAMS_DB.PUBLIC.STORE_TABLE STORE
ON SALES.STORE_ID = STORE.STORE_ID;


//VERIFY INITIAL LOAD
SELECT * FROM STREAMS_DB.PUBLIC.SALES_RAW_STAGING;

SELECT * FROM STREAMS_DB.PUBLIC.STORE_TABLE;

SELECT * FROM STREAMS_DB.PUBLIC.SALES_FINAL_TABLE;


//STREAM IMPLEMENTATION

//CREATE STREAM OBJECT
CREATE OR REPLACE STREAM STREAMS_DB.PUBLIC.SALES_STREAM
ON TABLE STREAMS_DB.PUBLIC.SALES_RAW_STAGING;

//VIEW STREAM INFORMATION
DESC STREAM STREAMS_DB.PUBLIC.SALES_STREAM;
SELECT * FROM STREAMS_DB.PUBLIC.SALES_STREAM;

//INSERT NEW SALES RECORDS
INSERT INTO STREAMS_DB.PUBLIC.SALES_RAW_STAGING VALUES
    (6, 'Mango', 1.99, 1, 2),
    (7, 'Garlic', 0.99, 1, 1);

//CHECK STRAM DATA
SELECT id, product, price, amount, store_id,
       METADATA$ACTION, METADATA$ISUPDATE, METADATA$ROW_ID
       FROM STREAMS_DB.PUBLIC.SALES_STREAM;

//VERIFY SOURCE AND TARGET TABLES
SELECT * FROM STREAMS_DB.PUBLIC.SALES_RAW_STAGING;
SELECT * FROM STREAMS_DB.PUBLIC.SALES_FINAL_TABLE;

//CONSUME STREAM DATA
INSERT INTO STREAMS_DB.PUBLIC.SALES_FINAL_TABLE
SELECT 
    STREAM.ID, STREAM.PRODUCT, STREAM.PRICE, STREAM.AMOUNT,
    STORE.STORE_ID, STORE.LOCATION, STORE.EMPLOYEES
FROM STREAMS_DB.PUBLIC.SALES_STREAM STREAM
JOIN STREAMS_DB.PUBLIC.STORE_TABLE STORE
ON STREAM.STORE_ID = STORE.STORE_ID
WHERE METADATA$ACTION = 'INSERT'
AND METADATA$ISUPDATE = FALSE;

SELECT * FROM STREAMS_DB.PUBLIC.SALES_FINAL_TABLE;

//VERIFY STREAM AFTER COMPLETION
SELECT * FROM STREAMS_DB.PUBLIC.SALES_STREAM;

//INSERT MORE SALES RECORDS
INSERT INTO STREAMS_DB.PUBLIC.SALES_RAW_STAGING VALUES 
    (8, 'Paparika', 4.99, 1, 2),
    (9, 'Tomato', 3.99, 1, 2);

//CONSUME SECOND STREAM DATA
SELECT * FROM STREAMS_DB.PUBLIC.SALES_STREAM;

INSERT INTO STREAMS_DB.PUBLIC.SALES_FINAL_TABLE
SELECT 
    STREAM.ID, STREAM.PRODUCT, STREAM.PRICE, STREAM.AMOUNT,
    STORE.STORE_ID, STORE.LOCATION, STORE.EMPLOYEES
FROM STREAMS_DB.PUBLIC.SALES_STREAM STREAM
JOIN STREAMS_DB.PUBLIC.STORE_TABLE STORE
ON STREAM.STORE_ID = STORE.STORE_ID
WHERE METADATA$ACTION = 'INSERT'
AND METADATA$ISUPDATE = FALSE;

// VERIFY FINAL INSERT OUTPUT
SELECT * FROM STREAMS_DB.PUBLIC.SALES_FINAL_TABLE;

SELECT * FROM STREAMS_DB.PUBLIC.SALES_RAW_STAGING;

SELECT * FROM STREAMS_DB.PUBLIC.SALES_STREAM;

// UPDATE CHANGE CAPTURE
//CHECK EXISTING DATA BEFORE UPDATE
SELECT * FROM STREAMS_DB.PUBLIC.SALES_RAW_STAGING;

SELECT * FROM STREAMS_DB.PUBLIC.SALES_STREAM;

// PERFORM FIRST UPDATE
UPDATE STREAMS_DB.PUBLIC.SALES_RAW_STAGING
SET PRODUCT = 'Potato' WHERE PRODUCT= 'Banana';

//CHECK STREAM AFTER UPDATE
SELECT * FROM STREAMS_DB.PUBLIC.SALES_STREAM;


//CONSUME UPDATE USING MERGE
MERGE INTO STREAMS_DB.PUBLIC.SALES_FINAL_TABLE F
USING (
        SELECT ID, PRODUCT, PRICE, AMOUNT, STORE_ID
        FROM STREAMS_DB.PUBLIC.SALES_STREAM
        WHERE METADATA$ACTION = 'INSERT'
        AND METADATA$ISUPDATE = 'TRUE'
) S 
ON F.ID = S.ID
WHEN MATCHED THEN 
UPDATE SET
    F.ID = S.ID,
    F.PRODUCT = S.PRODUCT,
    F.AMOUNT = S.AMOUNT,
    F.STORE_ID = S.STORE_ID;


// VERIFY FIRST UPDATE
SELECT * FROM STREAMS_DB.PUBLIC.SALES_FINAL_TABLE;

SELECT * FROM STREAMS_DB.PUBLIC.SALES_RAW_STAGING;

SELECT * FROM STREAMS_DB.PUBLIC.SALES_STREAM;

//SECOND UPDATE CHANGE CAPTURE
//PERFORM SECOND UPDATE
UPDATE STREAMS_DB.PUBLIC.SALES_RAW_STAGING
SET PRODUCT = 'Green Apple' where PRODUCT= 'Apple';

//CONSUME SECOND UPDATE USING MERGE
MERGE INTO STREAMS_DB.PUBLIC.SALES_FINAL_TABLE F
USING (
        SELECT STREAM.ID, STREAM.PRODUCT, STREAM.PRICE, STREAM.AMOUNT, STREAM.STORE_ID,
        STORE.LOCATION, STORE.EMPLOYEES
        FROM STREAMS_DB.PUBLIC.SALES_STREAM STREAM 
        JOIN STREAMS_DB.PUBLIC.STORE_TABLE STORE 
        ON STREAM.STORE_ID = STORE.STORE_ID
        WHERE METADATA$ACTION = 'INSERT'
        AND METADATA$ISUPDATE = TRUE
) S
ON S.ID = F.ID
WHEN MATCHED THEN 
UPDATE SET 
    F.ID = S.ID,
    F.PRODUCT = S.PRODUCT,
    F.PRICE = S.PRICE,
    F.AMOUNT = S.AMOUNT,
    F.STORE_ID = S.STORE_ID,
    F.LOCATION = S.LOCATION,
    F.EMPLOYEES = S.EMPLOYEES;


// VERIFY FINAL OUTPUT
SELECT * FROM STREAMS_DB.PUBLIC.SALES_FINAL_TABLE;

SELECT * FROM STREAMS_DB.PUBLIC.SALES_RAW_STAGING;

SELECT * FROM STREAMS_DB.PUBLIC.SALES_STREAM;